config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  resources :line_items
  resources :carts
  resources :books

  root 'books#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :line_items

  monetize :price_cents
  before_destroy :ensure_not_referenced_by_any_line_item


  scope :filter, -> (search) { where("title ILIKE ?", "%#{search}%") } 

  def add_book
    line_item = LineItem.new
  end
 

  private
  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy


  def add_book(book, quantity)
    current_item = line_items.find_by_book_id(book.id)
    if current_item && quantity > 0
      current_item.quantity += quantity
    else
      current_item = line_items.build(book_id: book.id, quantity: quantity)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end


end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book
  belongs_to :cart
  validates :quantity, inclusion: { in: (1..100) }

  def total_price
    book.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user
  PAYMENT_TYPES = [ "Visa", "MasterCard", "American Express" ] 
  validates :name, :shipping_address, :billing_address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  attr_accessor :stripe_card_token

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
    self.total = cart.total_price.cents
  end

  def save_with_payment(stripe_card_token)
    if valid?
      charge = Stripe::Charge.create(
        :amount => total,
        :currency => "usd",
        :source => stripe_card_token,
        :description => "Book order"
      )
      stripe_token = charge.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :orders

  before_create :save_to_stripe

  def cart
    orders.where(stripe_token: nil).first_or_create
  end

  def save_to_stripe
    if valid?
      customer = Stripe::Customer.create(email:  email)
      self.stripe_customer_token = customer.id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path
    end
  end
  helper_method :current_cart
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include CurrentCart

  before_filter :authenticate_user!
  before_action :set_cart

  def index
    sort = params[:sort] || "published_date desc"
    @books = Book.filter(params[:search])
      .order(sort)
      .page(params[:page])
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def new 
    @book = Book.new
  end

  private

  def book_params
      params.require(:book).permit(:id, :quantity)
    end

end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
  skip_before_action :authorize, only: :update

  def update
    @cart = Cart.find(params[:id])
    respond_to do |format|
      if @cart.id == session[:cart_id] && @cart.update(cart_params)
        redirect_to @cart, notice: 'Cart was successfully updated.' 
      else
        render :edit 
      end
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      redirect_to books_path, notice: 'Your cart is currently empty'
    end
  end

  private

    def cart_params
      params.require(:cart).permit(:book_id, :user_id, :cart_id, :quantity)
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private
  def set_cart
    begin
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  def create
    book = Book.find(params[:line_item][:book_id])
    quantity = params[:line_item][:quantity].to_i
    @line_item = @cart.add_book(book, quantity)

    if @line_item.save
      flash[:success] = "You successfully added #{book.title} to your cart!" 
      redirect_to books_path
    else
      flash[:error] = "Invalid quantity"
      redirect_to book_path(book) 
    end
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to edit_cart_path(@cart)
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authorize_access_to_order, only: [:show]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show

  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    @order.user = current_user
    @order.save

    CreditCard.create(card_params)


    redirect_to @order
  end

  def confirm_order
    if @order.save_with_payment
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil 
      OrderNotifier.received(@order).deliver       
      redirect_to @order, notice: "Thank you for your order!"
    else
      redirect_to @order, alert: "There was an error with placing your order: #{@order.errors.full_messages.to_sentence}"
    end
  end

  # PATCH/PUT /orders/1
  def update
    respond_to do |format|
      if @order.update(order_params)
        redirect_to @order, notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    respond_to do |format|
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
    end
  end

  private
    
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:name, :billing_address, :shipping_address,
                                    :email, :pay_type, :stripe_card_token)
    end

    def authorize_access_to_order
      if @order.user != current_user
        redirect_to root_path  
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert_message_class_for(flash_type)
    flash_alert_map = HashWithIndifferentAccess.new({
      success: 'success',
      error: 'danger',
      notice: 'info',
      warning: 'warning'
    })
    flash_alert_map[flash_type]
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/index.html.erb
<div class='log-out'>
<p><%= link_to "Your cart (#{@cart.line_items.count})", cart_path(@cart) %></p>
<p><%= link_to "Log out", destroy_user_session_path, :method => :delete %></p>
<p></div>
  <%= form_tag books_path, method: :get, class: 'form-inline' do %>
    <div class='form-group'>
      <%= text_field_tag :search, params[:search], class: 'form-control' %>
    </div>
    <%= submit_tag "Search", class: 'btn btn-default' %>
  <% end %>
</p>
<%= link_to "Sort by Most Popular", root_path(sort: "times_purchased") %></p>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published Date</th>
      <th>Price</th>
    </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td><%= book.author %></td>
      <td><%= book.published_date %></td>
      <td><%= book.price.format %></td>
      <td><%= link_to "Add to Cart", book_path(book) %></td>
    </tr>
    <% end %>
</table>

<%= paginate @books %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<p>Author: <%= @book.author %></p>
<p>Description: <%= @book.description %></p>
<div style="width:10%">
  <%= form_for :line_item, url: line_items_path do |f| %>
    Quantity: <%= f.text_field :quantity %>
    <%= f.hidden_field :book_id, value: @book.id %>
    <%= f.submit "Add to Cart" %>
  <% end %>
</div>
<p><%= link_to 'Home', :back %></p>

app/views/carts/_form.html.erb
<% if @cart.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
    <ul>
    <% @cart.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@cart) do |f| %>
  <table class='table'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    <% @cart.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.book.title %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.book.price %></td>
        <td><%= link_to 'Delete Item', line_item_path(line_item), method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', cart_path(@cart) %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%# <% if notice %>
<%#   <p id="notice"><%= notice %></p>
<%# <% end %>

<h2>Your cart</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Title</th>
      <th>Unit Price</th>
      <th>Total Price</th>
    </tr>
  <% @cart.line_items.each do |item| %>
    <tr>
      <td><%= item.quantity %> &times;</td>
      <td><%= item.book.title %></td>
      <td><%= item.book.price %></td>
      <td class="item_price"><%= number_to_currency(item.total_price) %></td>
    </tr>
  <% end %>

  <tr class="total_line">
    <td colspan="3">Total</td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>


<%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure?" } %>
<%= button_to 'Checkout', new_order_path, method: :get %>
  <%= link_to 'Edit', edit_cart_path(@cart) %> |
  <%= link_to 'Home', books_path %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= javascript_include_tag "https://js.stripe.com/v2/", "application" %>
  <%= csrf_meta_tags %>  
  <%= tag :meta, :name => "stripe-key", :content => :publishable_key %>
</head>
<body>
  <div class='container'>
    <header>
      <a href="/books"><h1>Speak Friend and Enter Bookstore</h1></a>
    </header>

    <div class='flash'>
      <% flash.each do |message_type, messages| %>
        <div class='alert alert-<%= bootstrap_alert_message_class_for(message_type) %>'>
          <ul class='<%= message_type %>'>
            <% [messages].flatten.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
</body>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item">
  <% else %>
    <tr>
    <% end %>
    <td><%= line_item.quantity %>&times;</td>
    <td><%= line_item.book.title %></td>
    <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
    </tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", 
            line_item.quantity,
            truncate(line_item.book.title, length: 50)) %>

app/views/line_items/edit.html.erb
<h2><%= @line_item.book.title %></h2>
<p>Author: <%= @line_item.book.author %></p>
<div style="width:10%">
  <%= form_for @line_item, url: line_item_path, method: :patch do |f| %>
    Quantity: <%= f.text_field :quantity, value: @line_item.quantity %>
    <%= f.hidden_field :book_id, value: @line_item.book.id %>
    <%= f.submit "Update Cart" %>
  <% end %>
</div>
<p><%= link_to 'Back', :back %></p>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.book %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @line_item.book %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %> | 
<%= link_to 'Home', books_path %>

app/views/order_notifier/received.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv='Content-Type'/>
  </head>
  <body>
<h1>Speak Friend and Enter Order Bookstore Received</h1>

<p>
<h1>Thank you for your recent order from the Speak Friend and Enter Bookstore!</h1>. 

You ordered the following items: 

<table>
  <tr><th colspan="2">Qty</th><th>Description</th></tr>
  <%= render @order.line_items -%>
</table>

We'll send you a separate email when your order ships.

</p>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from Speak Friend and Enter Bookstore. 

You ordered the following items: 

<%= render @order.line_items -%>

We'll send you a separate email when your order ships.

app/views/order_notifier/shipped.html.erb
<h1>Speak Friend and Enter Order Bookstore Shipped</h1>

<p>
  This is just to let you know that we've shipped your recent order:  
</p>

<table>
  <tr><th colspan="2">Qty</th><th>Description</th></tr>
  <%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
Dear <%= @order.name %>

Thank you for your recent order from Speak Friend and Enter Bookstore. We just wanted to let you know that we've shipped your recent order. 

You ordered the following items: 

<%= render @order.line_items -%>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :stripe_card_token %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_area :billing_address, rows: 3, cols: 40 %>
  </div>
   <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_area :shipping_address, rows: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :pay_type %><br>
    <%= f.select :pay_type, Order::PAYMENT_TYPES,
      prompt: 'Select a payment method' %>
</div>
 <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %><br>
    <%= text_field_tag :card_number, nil, name: nil %>
    <input type='hidden' id='last_four' name='order[last_four]'/>
  </div>
 <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %><br>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
 <div class="field">
    <%= label_tag :card_month, "Card Expiration" %><br>
    <%= select_month nil, { add_month_numbers: true }, { name: nil, id: "card_month" } %>
    <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+15 }, { name: nil, id: "card_year" } %>
  </div>
  <div id="stripe_error">
    <noscript>Javascript is not enabled and is required for this form. First enable it in your browser settings.</noscript>
  </div>
  <div class="actions">
    <%= f.submit 'Place Order' %>
  </div>
<% end %>

app/views/orders/confirmation.html.erb
<h1>Order Confirmation</h1>
<p>Please review your order below. If everything looks good, please click Confirm to place your order. Thanks!</p>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Total Price</th>
      <th>Quantity</th>
      <th>Order Total</th>
    </tr>
  </thead>
  <% @order.line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.book.title %></td>
      <td><%= line_item.total_price %></td>
      <td><%= line_item.quantity %></td>
  </tr>
  <% end %>

   <tr class="total_line">
    <td colspan="3">Total</td>
    <td class="total_cell"><%= @cart.total_price %></td>
  </tr>

</tbody>
</table>
<%= button_to 'Confirm', @order, :method => :post %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>
<div class="checkout_form">
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Order Summary</h1>
<div>
  <% @order.line_items.each do |line_item| %>
    <%= line_item.book.title %>
    <%= line_item.book.price_cents %>
    <%= line_item.quantity %>
    </br>
  <% end %>
</div>
</br>